# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/chrillep/github-action-summary/docs/production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Job summary (updated)
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
              .addHeading('Test Results')
              .addCodeBlock(`generateTestResults()`, "js")
              .addTable([
                [{data: 'File', header: true}, {data: 'Result', header: true}],
                ['foo.js', 'Passs '],
                ['bar.js', 'Fail '],
                ['test.js', 'Pass ']
              ])
              .addLink('View staging deployment!', 'https://github.com')
              .write()

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
      url: https://github.com/chrillep/github-action-summary/docs/development
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Job summary (updated)
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
              .addHeading('Test Results')
              .addCodeBlock(`generateTestResults()`, "js")
              .addTable([
                [{data: 'File', header: true}, {data: 'Result', header: true}],
                ['foo.js', 'Pass '],
                ['bar.js', 'Fail '],
                ['test.js', 'Pass ']
              ])
              .addLink('View staging deployment!', 'https://github.com')
              .write()
  staging:
    name: Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://github.com/chrillep/github-action-summary/docs/staging
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Job summary (updated)
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
              .addHeading('Test Results $')
              .addCodeBlock(`generateTestResults()`, "js")
              .addTable([
                [{data: 'File', header: true}, {data: 'Result', header: true}],
                ['foo.js', 'Pass '],
                ['bar.js', 'Fail '],
                ['test.js', 'Pass ']
              ])
              .addLink('View staging deployment!', 'https://github.com')
              .write()
      - name: Dump GitHub context
        id: github_context_step
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
              .addHeading('GitHub Context')
              .addCodeBlock(`${{ toJSON(github) }}`, "json")
              .write()
      - name: Dump job context
        id: job_context_step
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
              .addHeading('GitHub Job Context')
              .addCodeBlock(`${{ toJSON(job) }}`, "json")
              .write()
      - name: Dump steps context
        id: steps_context_step
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
              .addHeading('GitHub Steps Context')
              .addCodeBlock(`${{ toJSON(steps) }}`, "json")
              .write()
      - name: Dump runner context
        id: runner_context_step
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
              .addHeading('GitHub Runner Context')
              .addCodeBlock(`${{ toJSON(runner) }}`, "json")
              .write()
      - name: Dump strategy context
        id: strategy_context_step
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
              .addHeading('GitHub Strategy Context')
              .addCodeBlock(`${{ toJSON(strategy) }}`, "json")
              .write()
      - name: Dump matrix context
        id: matrix_context_step
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
              .addHeading('GitHub Matrix Context')
              .addCodeBlock(`${{ toJSON(matrix) }}`, "json")
              .write()
