name: lint
on: [pull_request]
jobs:
  remark-lint:
    name: runner / remark-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install remark presets
        run: npm install remark-toc remark-gfm remark-preset-lint-recommended remark-preset-lint-consistent
        shell: bash
      - name: remark-lint
        uses: reviewdog/action-remark-lint@v5
        with:
          reporter: github-pr-check
          remark_args: "--use remark-toc --use remark-gfm --use remark-preset-lint-consistent --use remark-preset-lint-recommended"
